norm_possible_categories = [
    "Adhesive",
    "Cable tie",
    "Connector",
    "Connector kit",
    "Connector accessories",
    "Backshell",
    "Backshell adapter",
    "Backshell strain relief clamp",
    "Cable support sleeve",
    "Cavity plug",
    "Connector contact",
    "Connector insert",
    "Connector jam nut",
    "Connector Band Clamp",
    "Connector dummy stowage",
    "Connector Grommet",
    "Connector Wedge Lock",
    "Contact member",
    "End cap",
    "Gasket",
    "Hardware",
    "Hose clamp",
    "Keying Pin",
    "Mounting clip",
    "Boot",
    "Safety wire",
    "Wire seal",
    "Shield split support ring",
    "Shield band",
    "Shrink boot",
    "Spacer",
    "Split Ring",
    "Strain relief accessory",
    "Tinel Lock Ring",
    "Device",
    "Device with 2 axial leads",
    "Fixing device",
    "Label",
    "Part selection",
    "Part selection by filter",
    "Part selection from set",
    "Segment/bundle materials",
    "Cable",
    "Flat ribbon cable",
    "Shielded cable",
    "Coaxial cable",
    "Differential pair cable",
    "Triaxial cable",
    "Cable gland",
    "Cable/wire connecction",
    "Insulation piercing connector",
    "Shield connector (splice)",
    "Solder sleeve device",
    "Splice (Inline)",
    "Ferrite",
    "Filler",
    "Fishnet",
    "Grommet",
    "Lacing tape",
    "Protective covering",
    "Convoluted tube",
    "Overbraid",
    "Shrink tube",
    "Shrink tube marker sleeve",
    "Sleeving",
    "Expando sleeve",
    "Fire protection sleeve",
    "Shrink transition",
    "Wire",
    "Tape",
    "Terminal lug",
    "Contact terminal",
    "Ferrule Terminal",
    "Ring Terminal",
    "Spade Terminal",
    "Tool",
    "Automated crimp tool",
    "Banding tool",
    "Connector contact insertion/removal tool",
    "Connector contact insertion tool",
    "connector contact removal tool",
    "Contact retention test tool",
    "Crimp tool",
    "Crimp tool positioner",
    "Latch disengaging tool",
    "Printer",
    "Torque adapter",
    "Unknown"
]

